---
- name: Pull in secrets file
  include_vars:
    name: secrets
    file: "{{playbook_dir}}/vars/secrets.yml"

- name: Delete existing central tools repo only if fixer is set
  file:
    path: "/{{vars.vars.directory}}/central_tools"
    state: absent
  when: fixer is defined

- name: Git Central Tools Repo
  git:
    repo: 'https://github.com/micgresham/central_tools.git'
    dest: "/{{vars.vars.directory}}/central_tools"
    update: no

- name: Add central_tools group
  group:
    name: central_tools
    state: present

- name: Add central_tools user
  user:
    name: central_tools
    home: "/{{vars.vars.directory}}/central_tools"
    create_home: True
    group: central_tools
    system: True

- name: Add airflow user
  user:
    name: airflow
    home: "/{{vars.vars.directory}}/airflow"
    create_home: True
    group: central_tools
    append: yes
    system: True 

- name: Change ownership
  file:
    recurse: yes
    path: "/{{vars.vars.directory}}/central_tools"
    owner: central_tools
    group: central_tools
    state: directory

- name: Stop mysql
  service:
    name: mysql
    state: stopped

- name: Make Directories
  file:
    path: "/{{vars.vars.directory}}/{{item}}"
    owner: mysql
    group: mysql
    state: directory
    mode: '0755'
  loop:
    - mysql

- name: Copy over files
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  loop:
    - {src: '{{playbook_dir}}/templates/mysql/mysqld.j2', dest: '/etc/mysql/mysql.conf.d/mysqld.cnf'}  
    - {src: '{{playbook_dir}}/templates/mysql/reader.j2', dest: '/etc/mysql/reader.cnf'}
    - {src: '{{playbook_dir}}/templates/mysql/scraper.j2', dest: '/etc/mysql/scraper.cnf'}
    - {src: '{{playbook_dir}}/templates/mysql/ct_gui_admin.j2', dest: '/etc/mysql/ct_gui_admin.cnf'}
    - {src: '{{playbook_dir}}/templates/mysql/ct_gui.j2', dest: '/etc/mysql/ct_gui.cnf'}

# note - ignore errors is on in case db has already been initialized
- name: Initialize mysql
  command: /usr/bin/sudo -u mysql /usr/sbin/mysqld --initialize --user=mysql --basedir=/opt/mysql --datadir=/opt/mysql/data
  ignore_errors: yes

- name: Get password
  shell: "grep 'A temporary password is generated for root@localhost' /var/log/mysql/error.log | awk -F ' ' '{print $(NF)}'"
  register: password

- name: Start mysql
  service:
    name: mysql
    state: started  

- name: debug
  debug:
    var: password

- name: Change password
  command: mysql --user root --password={{password.stdout}} --connect-expired-password --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY '{{secrets.mysql_root_password}}';"
  ignore_errors: yes

# Delete tables in case they were already created
- name: Delete tables
  ignore_errors: yes
  mysql_db:
    state: absent
    name: 
      - central_tools
      - central_tools_admin
    login_user: root
    login_password: "{{secrets.mysql_root_password}}"

- name: Import central_tools
  mysql_db:
    state: import
    target: "/{{vars.vars.directory}}/central_tools/central_tools.sql"
    name: all
    login_user: root
    login_password: "{{secrets.mysql_root_password}}"

# Delete users if they were already created
- name: Delete Users
  mysql_user:
    login_user: root
    login_password: "{{secrets.mysql_root_password}}"
    name: "{{item}}"
    host_all: yes
    state: absent
  loop:
    - scraper
    - reader
    - CT_GUI

- name: Import Users
  ignore_errors: yes
  mysql_db:
    state: import
    target: "/{{vars.vars.directory}}/central_tools/users.sql"
    name: central_tools
    login_user: root
    login_password: "{{secrets.mysql_root_password}}"

