---
- name: Pull in secrets file
  include_vars:
    name: secrets
    file: "{{playbook_dir}}/vars/secrets.yml"
    
- name: Pull in list of packages required in venv
  include_vars:
    name: venv_packages
    file: "{{playbook_dir}}/vars/venv_requirements.yml"

- name: Install required packages in venv
  pip:
    virtualenv: "/{{vars.vars.directory}}/central_tools/ct_venv"
    name: "{{item}}"
    virtualenv_command: "/usr/bin/python3 -m venv"
  loop: "{{venv_packages.requirements}}"

- name: Make django file executable
  file:
    path: "/{{vars.vars.directory}}/central_tools/manage.py"
    mode: 0755    

- name: Django makemigrations
  django_manage:
    command: makemigrations
    virtualenv: "/{{vars.vars.directory}}/central_tools/ct_venv"
    app_path: /opt/central_tools

- name: Django migrate
  django_manage:
    command: migrate
    database: auth_db
    virtualenv: "/{{vars.vars.directory}}/central_tools/ct_venv"
    app_path: /opt/central_tools

- name: Create an initial superuser.
  ignore_errors: yes
  django_manage:
    command: "createsuperuser --noinput --database=auth_db --noinput --username={{secrets.django_superuser_password}} --email={{secrets.django_superuser_email}}"
    app_path: /opt/central_tools
    virtualenv: "/{{vars.vars.directory}}/central_tools/ct_venv"
  environment:
    DJANGO_SUPERUSER_PASSWORD: "{{secrets.django_superuser_password}}"

