# Generated by Django 3.2.6 on 2022-04-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_centralsites_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='central_tokenID',
            field=models.CharField(default='', max_length=100),
        ),
    ]
