--- 
- name: Pull in list of packages
  include_vars:
    name: packages
    file: "{{playbook_dir}}/vars/package_requirements.yml"

# - name: Debug package list
#   debug:
#     msg: "{{item.key}} - {{item.value.version}}"
#   loop: "{{packages.required|dict2items}}"

- name: Install Required Packages
  package:
    name: "{{item.key}}"
    state: "{{item.value.version}}"
  loop: "{{packages.required|dict2items}}" 
  
- name: Purge Set Packages
  package:
    name: "{{item.key}}"
    state: absent
  loop: "{{packages.purge|dict2items}}"
  register: purge_status


- name: Set purged fact
  set_fact:
    purged: False

- name: See if anything was purged that requires reboot
  vars:
    package_name:
    reboot: "{{item.item.value.reboot}}"
    changed: "{{item.changed}}"
  set_fact:
    purged: "{{True if changed == True and reboot == 'y' else purged}}"
  loop: "{{ purge_status.results }}"

- name: Reboot if packaged purged that requires reboot
  reboot:
  when: purged == True


